version: '3'
services:
  db:
    image: postgres:latest
    container_name: db
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=fiap
      - POSTGRES_PASSWORD=fiap
      - POSTGRES_DB=bd_lanchonete
    volumes:
      - ./data:/data
  spring-app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: api 
    ports:
      - "8080:8080"
    depends_on:
      - db